name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/ubuntu/project-linkedin

            git pull origin main

            cd fastapi-auth

            source venv/bin/activate

            pip install -r requirements.txt

            alembic upgrade head

            sudo systemctl restart linkedin-backend

            sudo systemctl status linkedin-backend --no-pager

            echo "✅ Deployment completed successfully!"